### ISSUE TITLE
Css import Issues

### ISSUE THREAD

**Issue by vacaramin** [vacaramin/Virtual-Horizon#12]
Css in the frontend needs to be properly imported from the designated css files.

**Comment by vacaramin** [comment]
@awaismohammad23 This issue needs to fixed asap. More components being added would mean more coupling in code

**Comment by vacaramin** [comment]
This issue can be fixed with

Modular CSS
https://www.youtube.com/watch?v=ZawAwPYrxGA&ab_channel=TelmoSampaio

**Comment by vacaramin** [comment]
Or we can do another thing, that is for all new components we use modular stylesheets

**Comment by awaismohammad23** [comment]
Okay I'll work on this issue today
