### ISSUE TITLE
Message box position 

### ISSUE THREAD

**Issue by awaismohammad23** [vacaramin/Virtual-Horizon#26]
The message box position is not set accordingly the component for the message box is not looking great. Have a look at that once. I tried but I was not able to figure it out.

**Comment by vacaramin** [comment]
can you point out the file and the code where you have implemented this?

**Comment by vacaramin** [comment]
Ok @awaismohammad23 I'll look into this
I'll do my changes in a seperate branch, when I merge it with main, I'll notify you

**Comment by vacaramin** [comment]
@awaismohammad23 Try making a component when there is too much code to write so that it's modular and easy to edit and work with. preferably make as many components as possible so it's easier to move them around

**Comment by awaismohammad23** [comment]
Okay

**Comment by vacaramin** [comment]
Is this issue still persistent? @awaismohammad23 If not close this issue and add new issues that you see.

**Comment by awaismohammad23** [comment]
I will close this since the UI is changed for this now
