### ISSUE TITLE
Teacher's UI Incomplete and Routing required

### ISSUE THREAD

**Issue by awaismohammad23** [vacaramin/Virtual-Horizon#29]
The UI for the teacher must be created till the given deadline before 13th of October.

**Comment by vacaramin** [comment]
Routing within student dashboard is complete and merged in main, take a pull request
I'll fix the teacher board issue

**Comment by vacaramin** [comment]
I'll fix the teachers login view, Create multiple issues with teacher dashboard once I fix the login problem
